version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/app-config"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 99
