language: node_js

node_js:
  - '10'

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    # DOCKER_PASSWORD
    - secure: 'krHKVIFx8LrupJeZLfMK3PytUIKa/J4ngMQDJfyWxPUcvOIDxKq7sFoKbrTgllPINxTzUWl/yKcxgdFK3gs4iwytlcNaiWBfcnarUudl6/go8F2JspdDO3whTP8khSyqeVLJ0k3rtOhfgeeTBoluPi1HSPry/yOLOIksB1JrdouiIEyoFJIGyYk686W4/k3g/4/whlFEB3rnARVu9J3/2VsFxSZsYHn7pb+cNZDMTABKb6EgQIihuuy9kBYq4OSCzVwbHFyii1gucatbW8uaX6c7iAJCz8+h2dsi1IYHrsKehnYlyRQt/yfnZmzwwjXy2rwoZB55tUnUv1jo1m/353VVoQ4vleXeYvhpzKquTtcvfk/fMbmzEw9wJ8SNUK0EYdtfnkK8wo1RFcYX6lrPnKzR0p+JCvbAnO9sgaF04ucl8H0MMW3POq+2iss6MTIHFJfNbE6gOQwQp63posj+WeqqVpLmjq+bHktvXfv6r0nDvkAJjAoVv1PbP3JvduTakd7MOdvk/dYOs9xMDqs+a1K0yyf9LJxCtuqDqQgOVJRtvkHEUHWewFlFrwJWZjS9y8GEITPSvDlYIOGS/dyTvCCmdK+zvoXAeQih+VvYDKMRaangv8AbsGc+OykTQaLUsMFjf6a+TupgfkWM13r2hcFa0DlfsKu/S4PYJNuoKAQ='
    # DOCKER_USERNAME
    - secure: 'pO1pqKwfw0N5K539smGe22f0jHEWygvrmYVjxXEtNtaZRb6icjZ2TfJw/mDClHmeaAjmB2XIaga796AbArdZWdbEdfURZb8jlW2waH7hah82Y4cgkWyzi9+E42MCNPDkKDjCvgyqnQcmuRED0539gKDWqG8vxV1/YhkFbOP/28RDHWnplgubC5jZIsDWccCoLbzLp87BWH0ZY7RGKGukLsYsGzvaX5ZBE1p16g29PQxLtiJks578TufTyNY6Bwc1wXm604TPqXASXzbF/sCZ21oUG52G45GptmFnmCWhLJpmiUDYD92SEB2/TddeQDOiErGc0kAlQ5Io+bbAcYJXZAJeGNLOcPEY4X751vYKA/wVVewnMr0mt7QSJWAyLKxY+wOeJqRZE2aqiENbRU4XsaxlzZDvEno5DuDvmCuBfn98oBYjBt7HOZUMbMuoUHnOyWmkZEN9+bsXEjdSFYcgIaSztMDoO+52qFfX8IsRYyO+Hz0n3QMIX96Vrhkhm/rr8ABxk6EcjhUOftjX1+tTrTBSr3qeQQuC+JUBvGkDV2FG0HN8BTnBGKjenZkQVvd8QMWo7Xp4ObxYFNiwWpGjSGzgzHtCWMCnF/6/3lK0i6We+ypHHIk3fHxkRTG4BjiSz/hmLNlByn2lGg6hTsDsOc2JTYsGD87oIeqwNekNWfs='
  matrix:
    - DISTRIBUTION="$DISTRIBUTION_1"
    - DISTRIBUTION="wire"

notifications:
  email: false

# http://docs.travis-ci.com/user/build-lifecycle/
before_install:
  - echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config

after_success:
  - echo -e "$TRAVIS_COMMIT" > ./dist/commit
  - yarn build
  - |
    if [ "$TRAVIS_BRANCH" == "staging" ]; then
      if [ "$DISTRIBUTION" == "wire" ]; then
        yarn docker '' staging
      else
        yarn docker "$DISTRIBUTION" staging
      fi
    fi
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      if [ "$DISTRIBUTION" == "wire" ]; then
        yarn docker '' production
      else
        yarn docker "$DISTRIBUTION" production
      fi
    fi

deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    zip-file: dist/wire-account.zip
    access-key-id:
      secure: eph/s1GGgpaZj4+izIeADk5FSHkTqjTzSvO507pcdZKTclSG5rw3pp7yBxsRYj/gzyd895SEhjFUFxoYmeKP9pkC/SmcrV4z9gSOqXEGyUQBJPluxVEyfYsxL+bBO+E8X9Xk/rmayy7rGkKHC08KlKpSi4o8AjLqFcvrg0dRppFE2xBJtX25qbx4ghWY5AE9hGhh1yccxsCdZTZ0Bq0E8tyIW8K/Pi++koECBarn74jr5BBCjVOHhTlTfLPx/xqPcgL7Xg9R6w0KnMlSYMymdOsbMoKQcMGzxV37f1KEaL9sfVUSmL9hXmfKU4VHl+wOLi34Lf3ieDFK+AVBabOvlF8JfXrfo00T4wHADpTlyyPE59HHFsmRAK+G+bo+ZzycpWHQIB6d7jL/XRgKmv7gS3VqrDunWvI5pTuVrgBmiME3IWiE/ow2HiBgBzn4dmZSw8/zYjlXbO9HipjwmYFH9mw+h5/tYndaz9juP5gMYD7mkP0fWmfc5cfqLZj0GJSgbhBnP9KmvHL/GubmrMgTd2CAprlrrSlbASTKUw/ywW4f+91/jMeOen4V/ogjt2JNjHi0lru9oQAlQm+LVjob8Hx9tyNacga90dQ53Y/HEr5CoCbqFxogdiEcKNFjDWQ4RV2PPBbYGVQq9B2UFTQuUgHgQ028EH/WwJ7lCszs/T0=
    secret-access-key:
      secure: zIX568EVY/ZikO+e/llFPhx8L/gJYa51Y6hfkHbkXLZ0l2ytH6OXmtEsGx7e4vWS/wF7OBXno3dFhmlR7Fmp+Hq0d1mxOinw9BeB3PVbBrm0yKAZB0uq25Kurowymnp7A/JNQshPxn4hPj85SUd+J9v09FMX5Y1AHeB7S6I7/DtdhNixGLXekMlHWFacCdUwTeMUtt//VlJk/LAozgQPOAhmzvkkV5g+TgpGVN/FKKbiE0DOBXbwmiv9MjnFkIgNDgwl1wsXNteRthNCBSCLPVKx9/y5mAqNUFe6hQWfhYYkej42928hproCk6iNz3poRgV0FOzD2xEAC1mreYy3KFhwayAx8JIhpvUU5wTHeu7bLbIoILoqzVaXbdY9NVP92yrBsIDjv7aF0wvLq67gxIpVDWJZ6LcFRFkA6rumAsZD2IdcOI4/YNqqO7O06USJDhTDabYFlUB+KCObLvfxOu1mbXUJAuubY3WNN8d+ptFUWOqcCJt31jTiao/oNmjKL4r1IphJ9eGICrbZCVGCO4/OjuDLhh/F3dfxXQtKFDWdAjsY8osBX9jxeS450kAE+Vp+G/rB++t54cvY+oh0swGrut0F9YAwl+f+Z870ZyKH/hlo7aG6JyUAm9AxuxfrgmIK4uepLNhFlcIUniiYxIY8L5LwMk/OPv+jvLL4aWw=
    region: eu-central-1
    app: Account
    env: wire-account-prod
    bucket_name: wire-account-builds
    on:
      repo: wireapp/wire-account
      branch: master
      condition: $DISTRIBUTION = wire

  - provider: elasticbeanstalk
    skip_cleanup: true
    zip-file: dist/wire-account.zip
    access-key-id:
      secure: eph/s1GGgpaZj4+izIeADk5FSHkTqjTzSvO507pcdZKTclSG5rw3pp7yBxsRYj/gzyd895SEhjFUFxoYmeKP9pkC/SmcrV4z9gSOqXEGyUQBJPluxVEyfYsxL+bBO+E8X9Xk/rmayy7rGkKHC08KlKpSi4o8AjLqFcvrg0dRppFE2xBJtX25qbx4ghWY5AE9hGhh1yccxsCdZTZ0Bq0E8tyIW8K/Pi++koECBarn74jr5BBCjVOHhTlTfLPx/xqPcgL7Xg9R6w0KnMlSYMymdOsbMoKQcMGzxV37f1KEaL9sfVUSmL9hXmfKU4VHl+wOLi34Lf3ieDFK+AVBabOvlF8JfXrfo00T4wHADpTlyyPE59HHFsmRAK+G+bo+ZzycpWHQIB6d7jL/XRgKmv7gS3VqrDunWvI5pTuVrgBmiME3IWiE/ow2HiBgBzn4dmZSw8/zYjlXbO9HipjwmYFH9mw+h5/tYndaz9juP5gMYD7mkP0fWmfc5cfqLZj0GJSgbhBnP9KmvHL/GubmrMgTd2CAprlrrSlbASTKUw/ywW4f+91/jMeOen4V/ogjt2JNjHi0lru9oQAlQm+LVjob8Hx9tyNacga90dQ53Y/HEr5CoCbqFxogdiEcKNFjDWQ4RV2PPBbYGVQq9B2UFTQuUgHgQ028EH/WwJ7lCszs/T0=
    secret-access-key:
      secure: zIX568EVY/ZikO+e/llFPhx8L/gJYa51Y6hfkHbkXLZ0l2ytH6OXmtEsGx7e4vWS/wF7OBXno3dFhmlR7Fmp+Hq0d1mxOinw9BeB3PVbBrm0yKAZB0uq25Kurowymnp7A/JNQshPxn4hPj85SUd+J9v09FMX5Y1AHeB7S6I7/DtdhNixGLXekMlHWFacCdUwTeMUtt//VlJk/LAozgQPOAhmzvkkV5g+TgpGVN/FKKbiE0DOBXbwmiv9MjnFkIgNDgwl1wsXNteRthNCBSCLPVKx9/y5mAqNUFe6hQWfhYYkej42928hproCk6iNz3poRgV0FOzD2xEAC1mreYy3KFhwayAx8JIhpvUU5wTHeu7bLbIoILoqzVaXbdY9NVP92yrBsIDjv7aF0wvLq67gxIpVDWJZ6LcFRFkA6rumAsZD2IdcOI4/YNqqO7O06USJDhTDabYFlUB+KCObLvfxOu1mbXUJAuubY3WNN8d+ptFUWOqcCJt31jTiao/oNmjKL4r1IphJ9eGICrbZCVGCO4/OjuDLhh/F3dfxXQtKFDWdAjsY8osBX9jxeS450kAE+Vp+G/rB++t54cvY+oh0swGrut0F9YAwl+f+Z870ZyKH/hlo7aG6JyUAm9AxuxfrgmIK4uepLNhFlcIUniiYxIY8L5LwMk/OPv+jvLL4aWw=
    region: eu-central-1
    app: Account
    env: wire-account-staging
    bucket_name: wire-account-builds
    on:
      repo: wireapp/wire-account
      branch: staging
      condition: $DISTRIBUTION = wire
