name: Build & Deploy

on:
  push:
    branches: [staging]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        DISTRIBUTION: ['DISTRIBUTION_0', 'DISTRIBUTION_1']

    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
      DISTRIBUTION: ${{secrets[matrix.DISTRIBUTION]}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set BRANCH_NAME, TAG & COMMIT_MESSAGE environment variables
        run: |
          echo "::set-env name=BRANCH_NAME::$(git branch --show-current)"
          echo "::set-env name=TAG::$(git tag --points-at HEAD)"
          echo ::set-env name=COMMIT_MESSAGE::$(git log --format=%B -n 1 ${{github.event.after}})

      - name: Print env vars
        run: echo -e "COMMIT_MESSAGE = ${COMMIT_MESSAGE}, GITHUB_SHA = ${GITHUB_SHA}, TAG = ${TAG}, BRANCH_NAME = ${BRANCH_NAME}, GITHUB_REF = ${GITHUB_REF}"

      - name: Yarn cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Authenticate git clone
        run: echo -e "machine github.com\n  login ${GH_TOKEN}" > ~/.netrc

      - name: Install JS dependencies
        run: yarn --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Create commit file
        run: |
          mkdir -p ./dist
          echo -e "$GITHUB_SHA" > "./dist/commit"

      - name: Build
        run: |
          if [ "$BRANCH_NAME" == "staging" ]; then
            yarn bundle:staging
          elif [ "$BRANCH_NAME" == "master" ] && [ -n "$TAG" ]; then
            yarn bundle:prod
          fi

      - name: Deploy staging build to Elastic Beanstalk
        if: ${{ env.BRANCH_NAME == 'staging' && env.DISTRIBUTION == 'wire' }}
        uses: einaregilsson/beanstalk-deploy@v11
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: Account
          environment_name: wire-account-staging
          region: eu-central-1
          deployment_package: wire-account.zip
          wait_for_environment_recovery: 90
          version_label: ${{github.sha}}
          version_description: ${{env.COMMIT_MESSAGE}}

      - name: Deploy production build to Elastic Beanstalk
        if: ${{ env.BRANCH_NAME == 'master' && env.TAG != '' && env.DISTRIBUTION == 'wire' }}
        uses: einaregilsson/beanstalk-deploy@v11
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: Account
          environment_name: wire-account-prod
          region: eu-central-1
          deployment_package: wire-account.zip
          wait_for_environment_recovery: 90
          version_label: ${{env.TAG}}
          version_description: ${{env.COMMIT_MESSAGE}}

      - name: Push Docker image
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        run: |
          if [ "$BRANCH_NAME" == "staging" ]; then
            if [ "$DISTRIBUTION" == "wire" ]; then
              yarn docker '' staging
            else
              yarn docker "$DISTRIBUTION" staging
            fi
          elif [ "$BRANCH_NAME" == "master" ] && [ -n "$TAG" ]; then
            if [ "$DISTRIBUTION" == "wire" ]; then
              yarn docker '' production
            else
              yarn docker "$DISTRIBUTION" production
            fi
          fi
