name: Test, Build & Deploy

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        DISTRIBUTION: ['DISTRIBUTION_0', 'DISTRIBUTION_1']

    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
      DISTRIBUTION: ${{secrets[matrix.DISTRIBUTION]}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set BRANCH_NAME, TAG & COMMIT_MESSAGE environment variables
        run: |
          echo "::set-env name=BRANCH_NAME::$(git branch --show-current)"
          echo "::set-env name=TAG::$(git tag --points-at HEAD)"
          echo "::set-env name=COMMIT_MESSAGE::$(git log --format=%B -n 1 ${{github.event.after}})"

      - name: Print environment variables
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo -e "BRANCH_NAME = ${BRANCH_NAME}"
          echo -e "TAG = ${TAG}"
          echo -e "COMMIT_MESSAGE = ${COMMIT_MESSAGE}"
          echo -e "GITHUB_SHA = ${GITHUB_SHA}"
          echo -e "GITHUB_REF = ${GITHUB_REF}"
          echo -e "GITHUB_CONTEXT = ${GITHUB_CONTEXT}"

      - name: Yarn cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Authenticate git clone
        run: echo -e "machine github.com\n  login ${GH_TOKEN}" > ~/.netrc

      - name: Install JS dependencies
        run: yarn --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Create commit file
        run: |
          mkdir -p ./dist
          echo -e "$GITHUB_SHA" > "./dist/commit"

      - name: Build staging
        if: ${{ env.BRANCH_NAME == 'staging' }}
        run: yarn bundle:staging

      - name: Build production
        if: ${{ env.BRANCH_NAME == 'master' && env.TAG != '' }}
        run: yarn bundle:prod

      - name: Deploy staging build to Elastic Beanstalk
        if: ${{ env.BRANCH_NAME == 'staging' && env.DISTRIBUTION == 'wire' }}
        uses: einaregilsson/beanstalk-deploy@v11
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: Account
          environment_name: wire-account-staging
          region: eu-central-1
          deployment_package: wire-account.zip
          wait_for_environment_recovery: 90
          version_label: ${{github.sha}}
          version_description: ${{ format('"{0}"', env.COMMIT_MESSAGE) }}

      - name: Deploy production build to Elastic Beanstalk
        if: ${{ env.BRANCH_NAME == 'master' && env.TAG != '' && env.DISTRIBUTION == 'wire' }}
        uses: einaregilsson/beanstalk-deploy@v11
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: Account
          environment_name: wire-account-prod
          region: eu-central-1
          deployment_package: wire-account.zip
          wait_for_environment_recovery: 90
          version_label: ${{env.TAG}}
          version_description: ${{ format('"{0}"', env.COMMIT_MESSAGE) }}

      - name: Push staging Docker image
        if: ${{ env.BRANCH_NAME == 'staging' }}
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        run: |
          if [ "$DISTRIBUTION" == "wire" ]; then
            yarn docker '' staging
          else
            yarn docker "$DISTRIBUTION" staging
          fi

      - name: Push production Docker image
        if: ${{ env.BRANCH_NAME == 'master' && env.TAG != '' }}
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        run: |
          if [ "$DISTRIBUTION" == "wire" ]; then
            yarn docker '' production
          else
            yarn docker "$DISTRIBUTION" production
          fi
